apiVersion: v1
kind: Secret
metadata:
  name: theia-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ b64enc .Values.password }}
  user: {{ b64enc .Values.user }}

