apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      serviceAccountName: theia
      automountServiceAccountToken: true
      containers:
      - name: theia
        image: gashirar/theia-kubernetes:latest
        ports:
        - containerPort: 3000
        securityContext:
          privileged: true
---
kind: Service
apiVersion: v1
metadata:
  name: theia
spec:
  type: LoadBalancer
#  loadBalancerSourceRanges:
#  - <ADD YOUR IP ADDRESS>
  selector:
    app: theia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: theia
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: theia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: theia
subjects:
- kind: ServiceAccount
  name: theia
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: theia
